name: Event Admin

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: : actions/setup-java@v2
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk
        
        #steps:
      # - uses: actions/checkout@v1
      # - uses: actions/setup-java@v1
      #   with:
      #
      # - uses: subosito/flutter-action@v1
      # with:
      #  flutter-version: "2.0.0"

      # - run: flutter pub get
      # - run: flutter analyze .
      #- run: flutter test
    #- run: flutter build apk
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: release-apk
    #     path: build/app/outputs/apk/release/app-release.apk